- name: Copy a file
  hosts: web
  become: yes
  tasks:
    - name: Copy file.txt
      ansible.builtin.copy:
        src: /home/ec2-user/folder/file.txt  # Local path on the control machine
        dest: /home/ec2-user/folder2/file.txt  # Path on the target host
