- name: copy a file
  hosts: web
  become: yes
  tasks:
    - name: copy file.txt
      ansible.builtin.copy:
        remote_src: /home/ec2-user/folder/file.txt
        remote_dest: /home/ec2-user/folder2/