- name: install nginx on node server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started #ensures specified service is actively running
      enabled: yes #service starts automatically at boot time.
